import "./global.css";
import { PostProvider } from './context/PostContext';  // Ensure the path is correct

export const metadata = {
  title: "QuickCRUD",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PostProvider>
          {children}  
        </PostProvider>
      </body>
    </html>
  );
}
